sherlockode_sylius_faq_admin_category:
    resource: |
        alias: sherlockode_sylius_faq.category
        section: admin
        templates: "@SherlockodeSyliusFAQPlugin/admin/Category"
        redirect: update
        grid: sherlockode_sylius_faq_admin_category
        vars:
            index:
                icon: 'icon folder'
    type: sylius.resource

sherlockode_sylius_faq_admin_question:
    resource: |
        alias: sherlockode_sylius_faq.question
        section: admin
        templates: "@SherlockodeSyliusFAQPlugin/admin/Crud"
        redirect: update
        grid: sherlockode_sylius_faq_admin_question
        vars:
            index:
                icon: 'icon question circle outline'
    type: sylius.resource

sherlockode_sylius_faq_admin_category_remove_icon:
    path: /categories/{id}/remove-icon
    methods: [PUT]
    defaults:
        _controller: Sherlockode\SyliusFAQPlugin\Action\RemoveCategoryIconAction
