sherlockode_sylius_faq_admin_category:
    resource: |
        alias: sherlockode_sylius_faq.category
        section: admin
        templates: "@SherlockodeSyliusFAQPlugin/admin/Category"
        redirect: update
        except: ['show', 'index']
        grid: sherlockode_sylius_faq_admin_category
    type: sylius.resource

sherlockode_sylius_faq_admin_question:
    resource: |
        alias: sherlockode_sylius_faq.question
        section: admin
        templates: "@SherlockodeSyliusFAQPlugin/admin/Question"
        redirect: update
        except: ['show', 'index']
        grid: sherlockode_sylius_faq_admin_question
    type: sylius.resource

sherlockode_sylius_faq_admin_category_remove_icon:
    path: /categories/{id}/remove-icon
    methods: [PUT]
    defaults:
        _controller: Sherlockode\SyliusFAQPlugin\Action\RemoveCategoryIconAction
