imports:
    - { resource: "services.yaml" }
    - { resource: "sylius_grid.yaml" }
    - { resource: "sylius_resource.yaml" }
        
liip_imagine:
    filter_sets:
        sherlockode_faq_category_icon:
            filters:
                thumbnail: { size: [25, 25], mode: outbound }
