services:
    sherlockode_sylius_faq_menu_listener:
        class: Sherlockode\SyliusFAQPlugin\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

    app.faq_category_translation.form.type:
        class: Sherlockode\SyliusFAQPlugin\Form\Type\CategoryTranslationType
        tags:
            - { name: form.type }
        arguments: [ '%sherlockode_sylius_faq.model.category_translation.class%', [ 'sylius' ] ]

    app.faq_question_translation.form.type:
        class: Sherlockode\SyliusFAQPlugin\Form\Type\QuestionTranslationType
        tags:
            - { name: form.type }
        arguments: [ '%sherlockode_sylius_faq.model.question_translation.class%', [ 'sylius' ] ]

    sherlockode_sylius_faq.listener.category:
        class: Sherlockode\SyliusFAQPlugin\EventListener\CategoryListener
        arguments: 
             - '@sherlockode_sylius_faq.image_uploader'
             - '@liip_imagine.cache.manager'
             - '@liip_imagine.filter.manager'
        tags:
            - { name: kernel.event_listener, event: sherlockode_sylius_faq.category.pre_create, method: uploadImage }
            - { name: kernel.event_listener, event: sherlockode_sylius_faq.category.pre_update, method: uploadImage }
            - { name: doctrine.event_listener, event: onFlush, lazy: true }
            - { name: doctrine.event_listener, event: postFlush, lazy: true }
            - { name: doctrine.event_listener, event: prePersist, lazy: true }

    sherlockode_sylius_faq.listener.question:
        class: Sherlockode\SyliusFAQPlugin\EventListener\QuestionListener
        tags:
            - { name: doctrine.event_listener, event: prePersist, lazy: true }

    sherlockode_sylius_faq.image_uploader:
        class: Sherlockode\SyliusFAQPlugin\Uploader\ImageUploader
        arguments: 
            - '@Sylius\Component\Core\Filesystem\Adapter\FilesystemAdapterInterface'
            - '@Sylius\Component\Core\Generator\ImagePathGeneratorInterface'
    
    Sherlockode\SyliusFAQPlugin\Action\RemoveCategoryIconAction:
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@router'
            - '@security.csrf.token_manager'
            - '@sherlockode_sylius_faq.image_uploader'

    Sherlockode\SyliusFAQPlugin\Controller\FaqController:
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: controller.service_arguments }
                
    Sherlockode\SyliusFAQPlugin\Controller\Admin\ResourceController:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Sherlockode\SyliusFAQPlugin\Manager\ResourceManager'
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: controller.service_arguments }

    Sherlockode\SyliusFAQPlugin\Twig\Extension\TranslationExtension:
        tags:
            - { name: twig.extension }

    Sherlockode\SyliusFAQPlugin\Twig\TranslationRuntime:
        tags:
            - { name: twig.runtime }

    Sherlockode\SyliusFAQPlugin\Twig\Extension\TreeExtension:
        tags:
            - { name: twig.extension }

    Sherlockode\SyliusFAQPlugin\Twig\TreeRuntime:
        arguments:
            - '@router'
            - '@twig'
        tags:
            - { name: twig.runtime }
                
    Sherlockode\SyliusFAQPlugin\Twig\Extension\ResourceExtension:
        tags:
            - { name: twig.extension }
                
    Sherlockode\SyliusFAQPlugin\Twig\ResourceRuntime:
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: twig.runtime }

    Sherlockode\SyliusFAQPlugin\Manager\ResourceManager:
        arguments:
            - '@doctrine.orm.entity_manager'
