sylius_grid:
    grids:
        sherlockode_sylius_faq_admin_category:
            driver:
                name: doctrine/orm
                options:
                    class: Sherlockode\SyliusFAQPlugin\Entity\Category
            sorting:
                position: asc
            fields:
                position:
                    type: twig
                    label: sherlockode_sylius_faq.ui.category.position
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/position.html.twig"
                name:
                    type: string
                    label: sylius.ui.name
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
        sherlockode_sylius_faq_admin_question:
            driver:
                name: doctrine/orm
                options:
                    class: Sherlockode\SyliusFAQPlugin\Entity\Question
            sorting:
                position: asc
            fields:
                position:
                    type: twig
                    label: sherlockode_sylius_faq.ui.question.position
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/position.html.twig"
                question:
                    type: twig
                    label: sherlockode_sylius_faq.ui.question.question
                    options:
                        template: "@SherlockodeSyliusFAQPlugin/admin/Field/_question.html.twig"
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
