sylius_grid:
    grids:
        sherlockode_sylius_faq_admin_category:
            driver:
                name: doctrine/orm
                options:
                    class: Sherlockode\SyliusFAQPlugin\Entity\Category
                    repository:
                        method: createListQueryBuilder
                        arguments: [ "%locale%" ]
            sorting:
                position: asc
            # Contrary to what is found in the documentation (limits: ~), it is not possible to remove the pagination, there is no other choice
            # https://github.com/Sylius/SyliusGridBundle/blob/1.13/docs/your_first_grid.md#pagination
            limits: [1000]
            fields:
                position:
                    type: string
            actions:
                main:
                    create:
                        type: create
                        label: sherlockode_sylius_faq.ui.new_category
                item:
                    update:
                        type: update
                    delete:
                        type: delete
        sherlockode_sylius_faq_admin_question:
            driver:
                name: doctrine/orm
                options:
                    class: Sherlockode\SyliusFAQPlugin\Entity\Question
                    repository:
                        method: createListQueryBuilder
                        arguments: [ "%locale%" ]
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
